services:
  - type: web
    name: meal-optimization-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
